version: '3.1'
services:
  db:
    build: ./mysql
#    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    volumes:
      - .\mysql\conf\mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080