version: '3.1'
services:
  db:
    build: ./mysql
#    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    volumes:
      - .\mysql\conf\mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 18081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root