version: '3'
services:
  mongo:
    build: ../dockerfiles/mongo
    # image: 992189553983.dkr.ecr.ap-northeast-2.amazonaws.com/zimzua-mongo
    restart: always
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: zimzua
      MONGO_INITDB_ROOT_PASSWORD: zimzua

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 28081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: zimzua
      ME_CONFIG_MONGODB_ADMINPASSWORD: zimzua